### ISSUE TITLE
Fly parameters in mobile app

### ISSUE THREAD

**Issue by notsolowki** [mefistotelis/phantom-firmware-tools#14]
![tmp_28220-screenshot_20170122-154722-500770356](https://cloud.githubusercontent.com/assets/24588286/22186383/7e0943f2-e0ba-11e6-99c5-87b849fffa9d.png)

**Comment by notsolowki** [comment]
@mefistotelis do you think the esc are going to hold back on any extra throttle even if we get the app send the new values

**Comment by mefistotelis** [comment]
I don't know.

**Comment by notsolowki** [comment]
That max motor speed warning wasnt very promising

**Comment by notsolowki** [comment]
More interesting code for the RC
![tmp_28220-screenshot_20170122-1621422100798008](https://cloud.githubusercontent.com/assets/24588286/22186665/035c65a8-e0bf-11e6-8ce4-e1f593ed46ca.png)
![tmp_28220-screenshot_20170122-162148334068004](https://cloud.githubusercontent.com/assets/24588286/22186668/08c7a07a-e0bf-11e6-96f5-9dafd9cb6b18.png)
![tmp_28220-screenshot_20170122-162155-32208824](https://cloud.githubusercontent.com/assets/24588286/22186670/0e386fe4-e0bf-11e6-8b2d-2de6549181ca.png)
![tmp_28220-screenshot_20170122-1621591765842127](https://cloud.githubusercontent.com/assets/24588286/22186671/12d16466-e0bf-11e6-83cf-bf0582fe470a.png)
![tmp_28220-screenshot_20170122-162205-899649053](https://cloud.githubusercontent.com/assets/24588286/22186673/1741bce4-e0bf-11e6-980b-7642ce888437.png)

**Comment by notsolowki** [comment]
![tmp_28220-screenshot_20170122-162834474061890](https://cloud.githubusercontent.com/assets/24588286/22186716/e53a8bb2-e0bf-11e6-9649-99c25dec2cca.png)

**Comment by ferraript** [comment]
almost every picture you posted is from the part of the code that reads and writes TXT flight logs
I'm familiar with these classes as [I created converter](http://www.phantompilots.com/threads/tool-win-offline-txt-flightrecord-to-csv-converter.70428/) for TXT logs
but I lost track of what you are trying to achieve now

**Comment by notsolowki** [comment]
we need an app to be able to modify the flight controller parameters.i mean what else is left to do?

**Comment by notsolowki** [comment]
mefistotelis thinks that the flight controller variables are updated the the mobile app
