### ISSUE TITLE
MATRICE600PRO firmware MATRICE600PRO_FW_V01.00.01.20.bin request

### ISSUE THREAD

**Issue by eagleman111** [mefistotelis/phantom-firmware-tools#56]
Hi, Anyone can provide fw 1.20 for MATRICE600PRO?

**Comment by mefistotelis** [comment]
https://s3-ap-northeast-1.amazonaws.com/dji-firmware-test/M600PRO/MATRICE600PRO_FW_V01.00.01.20.bin
